export const POKEMONS_FETCH_STARTED = "POKEMONS_FETCH_STARTED";
export const POKEMONS_FETCH_SUCCESS = "POKEMONS_FETCH_SUCCES";
export const POKEMONS_FETCH_FAIL = "POKEMONS_FETCH_FAIL";
export const ADD_POKEMON = "ADD_POKEMON";
export const UPDATE_POKEMON = "UPDATE_POKEMON";
export const DELETE_POKEMON = "DELETE_POKEMON";

export const TYPES_FETCH_STARTED = "TYPES_FETCH_STARTED";
export const TYPES_FETCH_SUCCESS = "TYPES_FETCH_SUCCESS";
export const TYPES_FETCH_FAIL = "TYPES_FETCH_FAIL";
